name: the_chat_crew
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.0
  flutter_signin_button: ^1.1.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
